//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primera_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }

        internal bool Autenticar(string nombreUsuario, string contraseña)
        {
            throw new NotImplementedException();
        }

        public Nullable<int> HABILITADO { get; set; }
        public string TIPOUSUARIO { get; set; }
        public string ConfirmarClave { get; internal set; }
    }
}
